disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Sheldon Wright"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2, 2006"
description = "pursuing skill through practice and curiosity"
logo = "logo-32x32.png"

  [params.author]
  image = "sheldonwright.jpg"
  name = "Sheldon Wright"
  bio = "Linux System Administrator"
  headline = "Pursuing skill through practice and curiosity."

    [[params.author.links]]
    github = "https://github.com/sheldon-wright"

    [[params.author.links]]
    x-twitter = "https://x.com/sheldonxwright"

    [[params.author.links]]
    email = "mailto:hello@sheldonwright.dev"