disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Sheldon Wright"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2, 2006"
description = "Linux, Cloud, Code, and Automation"

[[params.author.links]]
github = "https://github.com/sheldon-wright"

[[params.author.links]]
x-twitter = "https://x.com/sheldonxwright"

[params.author]
image = "sheldonwright.jpg"
name = "Sheldon Wright"
bio = "Developer"
headline = "For me, the action is the juice."
