[[main]]
none = "none"

[[main]]
name = "GitHub"
# pre = "github"
url = "https://github.com/sheldon-wright"
identifier = "I1t1TT83sJ"
weight = 2

[[main]]
name = "Topics"
pageRef = "/topics"
identifier = "WgpbY580B4"
weight = 1

[[footer]]
none = "none"
